backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'service'
    label: 'Service'
    folder: 'content/Service'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Short Description', name: 'shortDescription', widget: 'string' }
      - { label: 'Icon', name: 'icon', widget: 'string' }